'use client';

import { useState } from 'react';
import Nav from '@/components/Nav';
import Card from '@/components/Card';
import { languages } from '@/lib/languages';

export default function AiInvoicePage() {
  const [text, setText] = useState('Create an invoice for Ahmed for garden cleaning, 3 hours, $180, due next Friday.');
  const [language, setLanguage] = useState('English');
  const [result, setResult] = useState<any>(null);
  const [loading, setLoading] = useState(false);

  async function generate() {
    setLoading(true);
    const res = await fetch('/api/ai-invoice', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ text, language, currency: 'AUD' }),
    });
    setResult(await res.json());
    setLoading(false);
  }

  return (
    <main className="min-h-screen bg-ink">
      <Nav />
      <section className="mx-auto grid max-w-6xl gap-6 px-6 py-8 md:grid-cols-2">
        <Card>
          <h1 className="text-3xl font-black">AI Invoice Creator</h1>
          <p className="mt-2 text-slate-400">Type naturally. AI turns it into a professional invoice.</p>
          <label className="mt-6 block text-sm font-bold text-slate-300">Invoice language</label>
          <select value={language} onChange={(e) => setLanguage(e.target.value)} className="mt-2 w-full rounded-2xl border border-line bg-card2 p-4 text-white">
            {languages.map((l) => <option key={l.code} value={l.label}>{l.flag} {l.label} — {l.nativeName}</option>)}
          </select>
          <label className="mt-6 block text-sm font-bold text-slate-300">What did you do?</label>
          <textarea value={text} onChange={(e) => setText(e.target.value)} className="mt-2 min-h-[180px] w-full rounded-2xl border border-line bg-card2 p-4 text-white" />
          <button onClick={generate} className="mt-5 w-full rounded-2xl bg-gradient-to-r from-violet-600 to-blue-500 py-4 font-black">{loading ? 'Generating...' : 'Generate Invoice'}</button>
        </Card>

        <Card>
          <h2 className="text-3xl font-black">Invoice Preview</h2>
          {!result ? <p className="mt-4 text-slate-400">Your invoice will appear here.</p> : (
            <div className="mt-6 rounded-2xl bg-white p-6 text-slate-900">
              <div className="flex justify-between">
                <div><h3 className="text-2xl font-black">INVOICE</h3><p className="text-sm text-slate-500">Generated by Invoix AI</p></div>
                <div className="text-right"><p className="font-bold">Currency: {result.currency}</p><p>Due: {result.dueDateText}</p></div>
              </div>
              <div className="mt-8"><p className="font-bold">Bill To</p><p>{result.customerName}</p><p>{result.customerPhone}</p><p>{result.customerEmail}</p></div>
              <table className="mt-8 w-full border-collapse">
                <thead><tr className="border-b"><th className="py-2 text-left">Description</th><th className="py-2 text-right">Qty</th><th className="py-2 text-right">Price</th><th className="py-2 text-right">Total</th></tr></thead>
                <tbody>{result.items?.map((item: any, i: number) => <tr key={i} className="border-b"><td className="py-3">{item.description}</td><td className="py-3 text-right">{item.quantity}</td><td className="py-3 text-right">${item.unitPrice}</td><td className="py-3 text-right">${Number(item.quantity) * Number(item.unitPrice)}</td></tr>)}</tbody>
              </table>
              <p className="mt-8 text-right text-2xl font-black">Total: ${result.items?.reduce((sum: number, item: any) => sum + Number(item.quantity) * Number(item.unitPrice), 0)}</p>
              <p className="mt-6 text-slate-600">{result.notes}</p>
            </div>
          )}
          {result && <button onClick={() => window.print()} className="mt-5 w-full rounded-2xl border border-line py-4 font-black">Print / Save PDF</button>}
        </Card>
      </section>
    </main>
  );
}
